

@startuml
title 1.Minishell_Sequence_Diagram
hide footbox

participant "main" as Main
participant "prompt" as Prompt
participant "cmd_manager" as CmdMgr
participant "pipe_executor" as PipeExe
participant "executor" as Exec
participant "redirect" as Redirect
participant "builtin" as Builtin

activate Main
loop
Main->Prompt: input_prompt\n入力待ち
activate Prompt
Prompt->Prompt: get_cmd_line\n入力文字列を受け取る
activate Prompt
note left: read\n標準入力待ち
deactivate Prompt
Prompt->CmdMgr: exec_one_line\n入力文字列の実行処理
activate CmdMgr
CmdMgr->CmdMgr: 入力文字列をセミコロン(;)で分割
loop Command Num times
	CmdMgr->PipeExe: fork_exec_command\n(パイプ含む)コマンド群実行処理
	activate PipeExe
	PipeExe->PipeExe: コマンド群をパイプ(|)で分割
	loop Pipe Num times
		PipeExe->PipeExe: exec_pipe_command\nコマンド実行処理
		activate PipeExe
		PipeExe->Exec: exec_command
		activate Exec
		loop Redirect Num times
			Exec->Redirect: separate_redirect_word\nリダイレクト指定
			activate Redirect
			Exec<--Redirect
			deactivate Redirect
		end
		Exec->Builtin: exec_xxx\nコマンド実行
		activate Builtin
		Exec<--Builtin
		deactivate Builtin
		PipeExe<--Exec
		deactivate Exec
		deactivate PipeExe
	end
	CmdMgr<--PipeExe
	deactivate PipeExe
end
Prompt<--CmdMgr
deactivate CmdMgr
Main<--Prompt
deactivate Prompt
end

deactivate Main



@enduml